-- ============================================================================
-- OBSOLETO. A função resumo_pedidos foi reescrita para ler da tabela-resumo
-- pré-agregada (muito mais rápida, sem timeout). A definição atual está em
-- supabase/pedidos_resumo_diario.sql — rode aquele arquivo.
-- (Este arquivo tinha a versão antiga que varria a tabela gorda de pedidos.)
-- ============================================================================
